services:
  - type: web
    name: damm-api
    env: docker
    plan: free
    rootDir: .
    branch: main
    buildCommand: docker build -f damm-world-api/Dockerfile -t damm-api .
    startCommand: docker run damm-api
    buildFilter:
      paths: ["damm-world-api/**", "shared/**", "lagoon-indexer/**"]
    envVars:
      - key: DATABASE_URL
        sync: true
      - key: OTHER_ENV
        sync: false

  - type: worker
    name: lagoon-indexer
    env: docker
    plan: free
    rootDir: .
    branch: main
    buildCommand: docker build -f lagoon-indexer/Dockerfile -t lagoon-indexer .
    startCommand: python indexer.py 11155111 10 2000 1 60
    buildFilter:
      paths: ["lagoon-indexer/**", "damm-world-api/**", "shared/**"]
    envVars:
      - key: DATABASE_URL
        sync: true

  - type: worker
    name: keeper-bot
    env: docker
    plan: free
    rootDir: .
    branch: main
    buildCommand: docker build -f bot/Dockerfile -t keeper-bot .
    startCommand: python keeper.py
    buildFilter:
      paths: ["bot/**", "lagoon-indexer/**", "damm-world-api/**", "shared/**"]
    envVars:
      - key: DATABASE_URL
        sync: true

databases:
  - name: lagoon-db
    plan: free
    databaseName: lagoon
    user: lagoon_user
