services:
  - type: web
    name: damm-api
    env: docker
    plan: free
    rootDir: .
    branch: main
    buildCommand: docker build -f damm-world-api/Dockerfile -t damm-api .
    startCommand: docker run damm-api
    buildFilter:
      paths: ["damm-world-api/**", "shared/**", "lagoon-indexer/**"]
    envVars:
      - key: DATABASE_URL
        sync: true
      - key: OTHER_ENV
        sync: false

  - type: worker
    name: lagoon-indexer
    env: docker
    plan: free
    rootDir: .
    branch: main
    buildCommand: docker build -f lagoon-indexer/Dockerfile -t lagoon-indexer .
    startCommand: python indexer.py --sleep_time 10 --range 2000 --real_time 1 --run_time 60
    buildFilter:
      paths: ["lagoon-indexer/**", "damm-world-api/**", "shared/**"]
    envVars:
      - key: DATABASE_URL
        sync: true
      - key: SUPPORTED_CHAINS
        value: "11155111,8453,10"

  - type: worker
    name: keeper-bot
    env: docker
    plan: free
    rootDir: .
    branch: main
    buildCommand: docker build -f bot/Dockerfile -t keeper-bot .
    startCommand: python keeper.py
    buildFilter:
      paths: ["bot/**", "lagoon-indexer/**", "damm-world-api/**", "shared/**"]
    envVars:
      - key: DATABASE_URL
        sync: true
      - key: API_URL
        value: https://damm-api.onrender.com
      - key: SUPPORTED_CHAINS
        value: "11155111,8453,10"

  - type: worker
    name: lagoon-migrate
    env: docker
    plan: free
    rootDir: .
    branch: main
    buildCommand: docker build -f lagoon-indexer/Dockerfile -t lagoon-migrate .
    startCommand: python db/run_schema.py
    autoDeploy: false
    buildFilter:
      paths: ["lagoon-indexer/**", "damm-world-api/**", "shared/**"]
    envVars:
      - key: DATABASE_URL
        sync: true

databases:
  - name: lagoon-db
    plan: free
    databaseName: lagoon
    user: lagoon_user
